# Generated by Django 4.1 on 2023-10-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Associate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Sub_department", models.CharField(max_length=50)),
                ("AIA_Avm", models.CharField(max_length=50)),
                ("Associate_ID", models.IntegerField()),
                ("Associate_Name", models.CharField(max_length=25)),
                ("Grade", models.CharField(max_length=10)),
                ("Bu_Classified", models.CharField(max_length=25)),
                ("Project_ID", models.IntegerField()),
                ("Project_Name", models.CharField(max_length=50)),
                ("Grid_Classification", models.CharField(max_length=25)),
                ("PM_ID", models.IntegerField()),
                ("PM_Name", models.CharField(max_length=25)),
                ("Account_ID", models.IntegerField()),
                ("Account_Name", models.CharField(max_length=25)),
                ("Parent_Customer_ID", models.IntegerField()),
                ("Parent_Customer", models.CharField(max_length=25)),
                ("Primary_Tag", models.CharField(max_length=25)),
                ("Secondary_Tag", models.CharField(max_length=25)),
                ("Home_Manager_ID", models.IntegerField()),
                ("Billability_Status", models.CharField(max_length=10)),
                ("Country", models.CharField(max_length=25)),
                ("State", models.CharField(max_length=25)),
                ("City", models.CharField(max_length=25)),
                ("Location_Description", models.CharField(max_length=25)),
                ("Ons_off", models.CharField(max_length=10)),
                ("Assignment_Start_Date", models.DateField()),
                ("Assignment_End_Date", models.DateField()),
                ("Assignment_Status", models.CharField(max_length=10)),
                ("Percent_Allocation", models.IntegerField()),
                ("Department_Name", models.CharField(max_length=25)),
                ("Sub_Vertical", models.CharField(max_length=25)),
                ("Project_Start_Date", models.DateField()),
                ("Project_End_Date", models.DateField()),
                ("Market_Na_GGM_Classified", models.CharField(max_length=25)),
                ("Market", models.CharField(max_length=25)),
                ("Market_Unit", models.CharField(max_length=25)),
                ("Poll_ID", models.IntegerField()),
            ],
        ),
    ]
