# Generated by Django 4.2.6 on 2023-10-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file_alter_associate_poll_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(max_length=20)),
                ('Emp_num', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=25)),
                ('Jan', models.IntegerField()),
                ('Feb', models.IntegerField()),
                ('Mar', models.IntegerField()),
                ('Apr', models.IntegerField()),
                ('May', models.IntegerField()),
                ('Jun', models.IntegerField()),
                ('Jul', models.IntegerField()),
                ('Aug', models.IntegerField()),
                ('Sep', models.IntegerField()),
                ('Oct', models.IntegerField()),
                ('Nov', models.IntegerField()),
                ('Dec', models.IntegerField()),
                ('Total', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
