# Generated by Django 4.2.6 on 2023-10-30 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_leave_apr_alter_leave_aug_alter_leave_dec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='id',
        ),
        migrations.AlterField(
            model_name='leave',
            name='Emp_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
