# Generated by Django 4.1 on 2023-11-01 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_remove_leave_id_alter_leave_emp_num"),
    ]

    operations = [
        migrations.DeleteModel(
            name="leave",
        ),
    ]
