# Generated by Django 4.1 on 2023-11-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_delete_leave"),
    ]

    operations = [
        migrations.CreateModel(
            name="leave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Team", models.CharField(max_length=20)),
                ("Emp_num", models.IntegerField()),
                ("Name", models.CharField(max_length=25)),
                ("Jan", models.IntegerField(default=0)),
                ("Feb", models.IntegerField(default=0)),
                ("Mar", models.IntegerField(default=0)),
                ("Apr", models.IntegerField(default=0)),
                ("May", models.IntegerField(default=0)),
                ("Jun", models.IntegerField(default=0)),
                ("Jul", models.IntegerField(default=0)),
                ("Aug", models.IntegerField(default=0)),
                ("Sep", models.IntegerField(default=0)),
                ("Oct", models.IntegerField(default=0)),
                ("Nov", models.IntegerField(default=0)),
                ("Dec", models.IntegerField(default=0)),
                ("Total", models.IntegerField(default=0)),
            ],
        ),
    ]
