# Generated by Django 4.1 on 2023-11-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_leave_emp_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associate",
            name="Associate_ID",
            field=models.IntegerField(unique=True),
        ),
    ]
