# Generated by Django 4.1 on 2023-11-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_associate_associate_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leave",
            old_name="Total",
            new_name="Total_Leaves",
        ),
        migrations.AlterField(
            model_name="associate",
            name="Poll_ID",
            field=models.IntegerField(),
        ),
    ]
