# Generated by Django 4.1 on 2023-11-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_rename_total_leave_total_leaves_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="Emp_num",
            field=models.IntegerField(),
        ),
    ]
