# Generated by Django 4.1 on 2023-11-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_alter_leave_emp_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="associate",
            name="Associate_ID",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="leave",
            name="Emp_num",
            field=models.IntegerField(unique=True),
        ),
    ]
